### ISSUE TITLE
After use "intended()" to assert the intent that attempt to launch other external activity, unable to continue next test

### ISSUE THREAD

**Issue by chungyusu** [google/android-testing-support-library#13]
I hit an issue while I tried to use intended() to verify the intent that is been sent by my app.
In Espresso test, after I perform click in my app to launch other external activity with an intent (assuming I am trying to launch HTML Viewer to view a text file from my app), then Espresso works good while I use intended() method to verify the intent that I passed while launching the external activity. However, the problem is that after I called intended(), the app focus will not get back to my app and I will not be able to continue my next test method if they are in the same class. Is there any way I can work around it?

**Comment by git1988** [comment]
Yes, Am facing the same.

**Comment by ldramire** [comment]
I've worked around this issue by using UiDevice.pressBack() to exit whatever activity or chooser has been presented. Note that you have to use UiDevice and not Espresso's pressBack method in order to interact with a component that is not part of your app's process.

**Comment by JoseAlcerreca** [comment]
Are you stubbing the Intent? 

https://github.com/googlesamples/android-testing/blob/master/ui/espresso/IntentsAdvancedSample/app/src/androidTest/java/com/example/android/testing/espresso/intents/AdvancedSample/ImageViewerActivityTest.java

(pressBack() is not a good idea, do not go that way!)

And please don't use this issue tracker, it's just for issues related to the site.
