### ISSUE TITLE
perform(click()) is doing a long press randomly and causing tests to fail

### ISSUE THREAD

**Issue by Hybryduk** [google/android-testing-support-library#15]
Espresso 2.2.1, Genymotion 2.6.0

We are using the perfom(click()) method to navigate through the application by selecting certain elements on screen. Randomly the click() method will long press on an object rather than just click and in that case it will cause tests to fail. This happens more frequently when pressing items in the action bar as they have help text. So rather than clicking on a share icon in the actionbar it will long press it and show the help text, causing the test to fail. 

We have also tried click(click()) as a work around, but that just causes most of the other tests to fail. If it does long press and it is successful, it will try and click again and the test will fail as the element is no longer there.

We are running are tests via Android Studio and it also happens when running through Gradle and adb.

What steps will reproduce the problem?
1. Have an app with a few pages to navigate through
2. Have a few tests to navigate through the application and test various part of the app

Outcome:
Tests will randomly fail do to long clicks when it is not expecting them.

Expected:
Remove the random long press and make the click() method consistent for tests.

Also posted this on the google page:
https://code.google.com/p/android/issues/detail?id=199544&thanks=199544&ts=1453722149

**Comment by slinzner** [comment]
Setting -> Accessibility -> Touch & hold delay

http://stackoverflow.com/questions/32330671/android-espresso-performs-longclick-instead-of-click
