### ISSUE TITLE
finish()/onDestroy() is not being called for every activity.

### ISSUE THREAD

**Issue by MichaelEvans** [google/android-testing-support-library#16]
This might not be a bug - (but I didn't see it documented anywhere) Is `finish()`/`onDestroy()` guaranteed to be called on every Activity started by ActivityTestRule, specifically in order? I'm seeing cases where `onDestroy()` is called, but the activity that's returning isn't being finished via `isFinishing()`. 

Some logs that show my findings: (`@Before` and `@After` are junit before/after methods)

```
D/OrderOfOp:    @Before        
D/OrderOfOp:    @After        
D/OrderOfOp:    onPause()        
D/OrderOfOp:    @Before        
D/OrderOfOp:    onDestroy()        
D/OrderOfOp:    onDestroy()    -->    isFinishing()
D/OrderOfOp:    @After        
D/OrderOfOp:    onPause()        
D/OrderOfOp:    @Before        
D/OrderOfOp:    @After        
D/OrderOfOp:    onPause()        
D/OrderOfOp:    @Before        
D/OrderOfOp:    onDestroy()        
D/OrderOfOp:    onDestroy()    -->    isFinishing()
D/OrderOfOp:    onPause()        
D/OrderOfOp:    onDestroy()        
D/OrderOfOp:    onDestroy()    -->    isFinishing()
```

(for reference, this is the onDestroy() method):
```
 @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d("OrderOfOp", "onDestroy()");
        if (isFinishing()) {
            Log.d("OrderOfOp", "onDestroy() --> isFinishing()");
        }
    }
```

**Comment by LShuttneab** [comment]
@JoseAlcerreca what is the correct forum?

**Comment by JoseAlcerreca** [comment]
The correct forum is in https://google.github.io/android-testing-support-library/support/index.html

but we're looking into it.

**Comment by slinzner** [comment]
This has been addressed in the next release!

**Comment by virusman** [comment]
I just wasted 4 hours of my life on this. Is there a workaround for the time being?

**Comment by DreierF** [comment]
Is there any release date for 0.6?
The last version as of now was 0.5 from 2016-02-22
