### ISSUE TITLE
Issue with site. Clicking selects all texts.

### ISSUE THREAD

**Issue by thupten1234** [google/android-testing-support-library#17]
There is text selection issue on the website.
Url https://google.github.io/android-testing-support-library/docs/espresso/basics/index.html
Issue
 clicking on content select all text on the site. only way to unselect seems like doubleclick. 

Using firefox 44.0 on linux mint cinnamon

**Comment by slinzner** [comment]
Any update on this @JoseAlcerreca

**Comment by knezmilos13** [comment]
Also on Firefox 47 and 48 on Windows 7... It's quite infuriating, I have to view page source to copy code snippets...

**Comment by JoseAlcerreca** [comment]
Sorry I totally missed this, I can reproduce with Firefox on Linux. WIP.

**Comment by JoseAlcerreca** [comment]
Fixed, tested in FF 47.0. Can you confirm @knezmilos13, @thupten1234?

**Comment by knezmilos13** [comment]
Looks good here. Thanks!

**Comment by JoseAlcerreca** [comment]
Thank you!
