### ISSUE TITLE
ServiceTestRule latch bug

### ISSUE THREAD

**Issue by alebiker** [google/android-testing-support-library#20]
If we run more Test with same ServiceTestRule object, the bindAndWait function it will test the status of `public static CountDownLatch mConnectedLatch = new CountDownLatch(1);` that is initialized only on first run of ServiceTestRule.
So the first run, the bindAndWait waits correctly the connection establishment, the next runs, will not, because the latch is 0.
Makes  the property  not static seems it solve the bug.

**Comment by slinzner** [comment]
Can you please file a bug here: https://code.google.com/p/android/issues/entry?template=Test%20Support%20Library%20bug
