### ISSUE TITLE
Espresso:Overslept and turned a tap into a long press

### ISSUE THREAD

**Issue by Tgillon** [google/android-testing-support-library#26]
Hi,
We have a flaky tests suite for a specific activity due to the following error:
"Overslept and turned a tap into a long press"
I have to mention that this activity has multiple fragments and by clicking on the bottom tab bar we navigate between the fragments.
sometimes clicking on one of the bar items becomes along click and the test fails.
any plans to fix it soon?
any suggestions besides rollback action?
Thanks,
Tali

**Comment by JoseAlcerreca** [comment]
Hi Tgillon,

Please check out https://google.github.io/android-testing-support-library/support/index.html to route your question to the appropriate channel.
