### ISSUE TITLE
Documentation link missing.

### ISSUE THREAD

**Issue by ldramire** [google/android-testing-support-library#5]
Minor documentation bug (and if there's a better way to file these types of issue, please let me know).

https://google.github.io/android-testing-support-library/docs/espresso/basics/index.html#finding-a-view-with-onview

Last line of the first paragraphs reads "If you are not familiar with hamcrest matchers, we suggest you start with a quick look at this presentation.".

Expected: a link or embedded object for "this presentation".
Actual: no link or embedded object is provided for "this presentation", leading to confusion and sadness.

**Comment by JoseAlcerreca** [comment]
Fixed, the link is http://www.slideshare.net/shaiyallin/hamcrest-matchers

Thank you Luis!

**Comment by ldramire** [comment]
Damn, now that's what I call service. Thanks!
