### ISSUE TITLE
IntentsTestRule throws null pointer exception when started without launch activity flag

### ISSUE THREAD

**Issue by ldramire** [google/android-testing-support-library#8]
Bug file here, but this seems like the more appropriate place for it:
https://code.google.com/p/android/issues/detail?id=187249

**Comment by slinzner** [comment]
Moved the bug to the right component. For future reference, the correct component is "Component-Test-Support-Libraries": https://code.google.com/p/android/issues/list?can=1&q=label%3AComponent-Test-Support-Libraries
