### ISSUE TITLE
Where can I find the original issues?

### ISSUE THREAD

**Issue by cgcgbcbc** [google/android-testing-support-library#9]
For example, https://code.google.com/p/android-test-kit/issues/detail?id=136

**Comment by Takhion** [comment]
That's also the issue I'm looking for!

**Comment by nkoroste** [comment]
Everything was moved to b.android.com under Test-Support-Libraries
component:

bugs:
https://code.google.com/p/android/issues/list?can=2&q=label%3AComponent-Test-Support-Libraries%20label%3AType-Defect

features:
https://code.google.com/p/android/issues/list?can=2&q=label%3AComponent-Test-Support-Libraries+label%3AType-Enhancement&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles

**Comment by cgcgbcbc** [comment]
But I remember that the issue I was referring to stated the following solution to some problem
```
configurations.all {
        resolutionStrategy.force 'com.android.support:support-annotations:22.2.1'
}
```
But I can't find any issue related to this topic.

**Comment by nkoroste** [comment]
This issue was fixed in the later version of the ATSL. Unfortunately,
old-fixed issues were lost during the migration. If you believe this issue
still exists please open a new bug under the new component in b.androd.com.
Thank you!

**Comment by JoseAlcerreca** [comment]
I'll close this as it's not an issue on the ATSL page (please use the mailing list).
